testing validation

diff --git a/.github/workflows/terraform-firewall-rule-validation.yaml b/.github/workflows/terraform-firewall-rule-validation.yaml
--- a/.github/workflows/terraform-firewall-rule-validation.yaml
+++ b/.github/workflows/terraform-firewall-rule-validation.yaml
@@ -10,18 +10,32 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  firewall-rules-lint:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # firewall-rules-lint:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Run Super-Linter
-        uses: github/super-linter/slim@v4
-        env:
-          VALIDATE_JSON: true
-          FILTER_REGEX_INCLUDE: rules/.+\.json$
-          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Install jsonlint
+  #       run: npm install -g jsonlint
+
+  #     - name: Get list of changed files
+  #       id: check_files_changed
+  #       uses: actions/github-script@v7
+  #       with:
+  #         script: |
+  #           const script = require('./.github/scripts/terraform-schema-check/get_list_changed_files.js')
+  #           return await script({github, context, core})
+
+  #     - name: Run jsonlint
+  #       run: find rules -name '*.json' -print0 | xargs -0 jsonlint -qw
+
+  #     # - name: Run Super-Linter
+  #     #   uses: github/super-linter/slim@v4
+  #     #   env:
+  #     #     VALIDATE_JSON: true
+  #     #     FILTER_REGEX_INCLUDE: rules/.+\.json$
+  #     #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   firewall-rules-schema-check:
     runs-on: ubuntu-latest
@@ -52,8 +66,8 @@ jobs:
             const script = require('./.github/scripts/terraform-schema-check/get_list_changed_files.js')
             return await script({github, context, core})
 
-      - name: Schema Validation
-        id: schema_validation
+      - name: JSON Lint & Schema Validation
+        id: json_lint_and_schema_validation
         uses: actions/github-script@v7
         with:
           script: |
@@ -62,7 +76,20 @@ jobs:
             return await script({github, context, core, changedFiles})
         continue-on-error: true
 
+      - name: Check for JSON Lint Errors
+        id: check_for_json_lint_errors
+        run: |
+          errors=$(echo '${{ steps.json_lint_and_schema_validation.outputs.jsonLintErrors }}' | jq -r '.')
+          error_count=$(echo "$errors" | jq 'length')
+          if [ "$error_count" -gt 0 ]; then
+            echo "JSON Lint Errors found in the following files:"
+            echo "$errors" | jq -r '.[] | "- \(.file): \(.error)"'
+            exit 1
+          fi
+        shell: bash
+
   firewall-rules-opa-check:
+    needs: [firewall-rules-schema-check]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -70,7 +97,11 @@ jobs:
 
   pull-request-approver:
     runs-on: ubuntu-latest
-    needs: [firewall-rules-lint, firewall-rules-schema-check, firewall-rules-opa-check]
+    needs: [
+        # firewall-rules-lint,
+        firewall-rules-schema-check,
+        firewall-rules-opa-check,
+      ]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
